# Use an official Node.js runtime as the base image
FROM node:lts-alpine3.9

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY ./.env ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3000

# Build the Node.js application
RUN npm run build

# Set the environment variable for production
ENV NODE_ENV=production

# Specify the command to start the application in production mode
CMD [ "node", "dist/app.js" ]
