# Use an official Node.js runtime as the base image
FROM node:20.14-alpine3.20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3000

# Specify the command to start the application in production mode
CMD [ "node", "app.js" ]
